# Generated by Django 4.2.7 on 2026-05-20 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_goal', models.IntegerField(default=2000)),
                ('daily_protein_goal', models.FloatField(default=50)),
                ('daily_carbs_goal', models.FloatField(default=250)),
                ('daily_fat_goal', models.FloatField(default=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('predicted_food', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('calories_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField()),
                ('carbs_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('estimated_portion_g', models.FloatField(default=100)),
                ('estimated_calories', models.FloatField()),
                ('estimated_protein', models.FloatField()),
                ('estimated_carbs', models.FloatField()),
                ('estimated_fat', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Food Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
